
import type { Celebrity } from './types';

export const celebritiesData: Celebrity[] = [
  // Hollywood Couples
  { id: '1', type: 'celebrity', name: 'Justin Bieber', imageUrl: '/images/celebrities/Justin Bieber.png', partner: 'Hailey Bieber', exes: ['Selena Gomez'] },
  { id: '2', type: 'celebrity', name: 'Hailey Bieber', imageUrl: '/images/celebrities/Hailey Bieber.png', partner: 'Justin Bieber', exes: [] },
  { id: '3', type: 'celebrity', name: 'Taylor Swift', imageUrl: '/images/celebrities/Taylor Swift.png', partner: 'Travis Kelce', exes: ['Harry Styles', 'The Weeknd'] },
  { id: '4', type: 'celebrity', name: 'Travis Kelce', imageUrl: '/images/celebrities/Travis Kelce.png', partner: 'Taylor Swift', exes: [] },
  { id: '5', type: 'celebrity', name: 'Blake Lively', imageUrl: '/images/celebrities/Blake Lively.png', partner: 'Ryan Reynolds', exes: [] },
  { id: '6', type: 'celebrity', name: 'Ryan Reynolds', imageUrl: '/images/celebrities/Ryan Reynolds.png', partner: 'Blake Lively', exes: [] },
  { id: '7', type: 'celebrity', name: 'Beyonce', imageUrl: '/images/celebrities/Beyonce.png', partner: 'Jay-Z', exes: [] },
  { id: '8', type: 'celebrity', name: 'Jay-Z', imageUrl: '/images/celebrities/Jay-Z.png', partner: 'Beyonce', exes: [] },
  { id: '9', type: 'celebrity', name: 'Tom Holland', imageUrl: '/images/celebrities/Tom Holland.png', partner: 'Zendaya', exes: [] },
  { id: '10', type: 'celebrity', name: 'Zendaya', imageUrl: '/images/celebrities/Zendaya.png', partner: 'Tom Holland', exes: [] },
  { id: '25', type: 'celebrity', name: 'Mila Kunis', imageUrl: '/images/celebrities/Mila Kunis.png', partner: 'Ashton Kutcher', exes: [] },
  { id: '26', type: 'celebrity', name: 'Ashton Kutcher', imageUrl: '/images/celebrities/Ashton Kutcher.png', partner: 'Mila Kunis', exes: [] },
  { id: '27', type: 'celebrity', name: 'Chrissy Teigen', imageUrl: '/images/celebrities/Chrissy Teigen.png', partner: 'John Legend', exes: [] },
  { id: '28', type: 'celebrity', name: 'John Legend', imageUrl: '/images/celebrities/John Legend.png', partner: 'Chrissy Teigen', exes: [] },
  { id: '29', type: 'celebrity', name: 'Jessica Biel', imageUrl: '/images/celebrities/Jessica Biel.png', partner: 'Justin Timberlake', exes: [] },
  { id: '30', type: 'celebrity', name: 'Justin Timberlake', imageUrl: '/images/celebrities/Justin Timberlake.png', partner: 'Jessica Biel', exes: ['Britney Spears'] },

  // Hollywood Exes & Fillers
  { id: '11', type: 'celebrity', name: 'Selena Gomez', imageUrl: '/images/celebrities/Selena Gomez.png', exes: ['Justin Bieber', 'The Weeknd'] },
  { id: '12', type: 'celebrity', name: 'Shawn Mendes', imageUrl: '/images/celebrities/Shawn Mendes.png', exes: [] },
  { id: '13', type: 'celebrity', name: 'Drake', imageUrl: '/images/celebrities/Drake.png', exes: [] },
  { id: '14', type: 'celebrity', name: 'Kendall Jenner', imageUrl: '/images/celebrities/Kendall Jenner.png', exes: [] },
  { id: '15', type: 'celebrity', name: 'Leonardo DiCaprio', imageUrl: '/images/celebrities/Leonardo DiCaprio.png', exes: [] },
  { id: '16', type: 'celebrity', name: 'Scarlett Johansson', imageUrl: '/images/celebrities/Scarlett Johansson.png', exes: [] },
  { id: '17', type: 'celebrity', name: 'Harry Styles', imageUrl: '/images/celebrities/Harry Styles.png', exes: ['Taylor Swift'] },
  { id: '18', type: 'celebrity', name: 'Rihanna', imageUrl: '/images/celebrities/Rihanna.png', exes: [] },
  { id: '19', type: 'celebrity', name: 'The Weeknd', imageUrl: '/images/celebrities/The Weeknd.png', exes: ['Selena Gomez', 'Taylor Swift'] },
  { id: '20', type: 'celebrity', name: 'Gigi Hadid', imageUrl: '/images/celebrities/Gigi Hadid.png', exes: [] },
  { id: '21', type: 'celebrity', name: 'Dua Lipa', imageUrl: '/images/celebrities/Dua Lipa.png', exes: [] },
  { id: '22', type: 'celebrity', name: 'Chris Evans', imageUrl: '/images/celebrities/Chris Evans.png', exes: [] },
  { id: '23', type: 'celebrity', name: 'Jennifer Lawrence', imageUrl: '/images/celebrities/Jennifer Lawrence.png', exes: [] },
  { id: '24', type: 'celebrity', name: 'Timothée Chalamet', imageUrl: '/images/celebrities/Timothée Chalamet.png', exes: [] },
  { id: '31', type: 'celebrity', name: 'Kim Kardashian', imageUrl: '/images/celebrities/Kim Kardashian.png', exes: ['Kanye West'] },
  { id: '32', type: 'celebrity', name: 'Kanye West', imageUrl: '/images/celebrities/Kanye West.png', exes: ['Kim Kardashian'] },
  { id: '33', type: 'celebrity', name: 'Brad Pitt', imageUrl: '/images/celebrities/Brad Pitt.png', exes: ['Angelina Jolie', 'Jennifer Aniston'] },
  { id: '34', type: 'celebrity', name: 'Angelina Jolie', imageUrl: '/images/celebrities/Angelina Jolie.png', exes: ['Brad Pitt'] },
  { id: '35', type: 'celebrity', name: 'Jennifer Aniston', imageUrl: '/images/celebrities/Jennifer Aniston.png', exes: ['Brad Pitt'] },
  { id: '36', type: 'celebrity', name: 'Britney Spears', imageUrl: '/images/celebrities/Britney Spears.png', exes: ['Justin Timberlake'] },
  { id: '37', type: 'celebrity', name: 'Ariana Grande', imageUrl: '/images/celebrities/Ariana Grande.png', exes: [] },
  { id: '38', type: 'celebrity', name: 'Lady Gaga', imageUrl: '/images/celebrities/Lady Gaga.png', exes: [] },
  { id: '39', type: 'celebrity', name: 'Chris Hemsworth', imageUrl: '/images/celebrities/Chris Hemsworth.png', exes: [] },
  { id: '40', type: 'celebrity', name: 'Margot Robbie', imageUrl: '/images/celebrities/Margot Robbie.png', exes: [] },

  // Russian Couples
  { id: '41', type: 'celebrity', name: 'Alla Pugacheva', imageUrl: '/images/celebrities/Alla Pugacheva.png', partner: 'Maxim Galkin', exes: ['Philipp Kirkorov'] },
  { id: '42', type: 'celebrity', name: 'Maxim Galkin', imageUrl: '/images/celebrities/Maxim Galkin.png', partner: 'Alla Pugacheva', exes: [] },
  { id: '43', type: 'celebrity', name: 'Pavel Volya', imageUrl: '/images/celebrities/Pavel Volya.png', partner: 'Laysan Utiasheva', exes: [] },
  { id: '44', type: 'celebrity', name: 'Laysan Utiasheva', imageUrl: '/images/celebrities/Laysan Utiasheva.png', partner: 'Pavel Volya', exes: [] },
  { id: '45', type: 'celebrity', name: 'Ksenia Sobchak', imageUrl: '/images/celebrities/Ksenia Sobchak.png', partner: 'Konstantin Bogomolov', exes: ['Maxim Vitorgan'] },
  { id: '46', type: 'celebrity', name: 'Konstantin Bogomolov', imageUrl: '/images/celebrities/Konstantin Bogomolov.png', partner: 'Ksenia Sobchak', exes: [] },
  { id: '47', type: 'celebrity', name: 'Fedor Bondarchuk', imageUrl: '/images/celebrities/Fedor Bondarchuk.png', partner: 'Paulina Andreeva', exes: [] },
  { id: '48', type: 'celebrity', name: 'Paulina Andreeva', imageUrl: '/images/celebrities/Paulina Andreeva.png', partner: 'Fedor Bondarchuk', exes: [] },
  { id: '49', type: 'celebrity', name: 'Agata Muceniece', imageUrl: '/images/celebrities/Agata Muceniece.png', exes: ['Pavel Priluchny'] },
  { id: '50', type: 'celebrity', name: 'Pavel Priluchny', imageUrl: '/images/celebrities/Pavel Priluchny.png', exes: ['Agata Muceniece'] },

  // Russian Exes & Fillers
  { id: '51', type: 'celebrity', name: 'Philipp Kirkorov', imageUrl: '/images/celebrities/Philipp Kirkorov.png', exes: ['Alla Pugacheva'] },
  { id: '52', type: 'celebrity', name: 'Maxim Vitorgan', imageUrl: '/images/celebrities/Maxim Vitorgan.png', exes: ['Ksenia Sobchak'] },
  { id: '53', type: 'celebrity', name: 'Ivan Urgant', imageUrl: '/images/celebrities/Ivan Urgant.png', exes: [] },
  { id: '54', type: 'celebrity', name: 'Danila Kozlovsky', imageUrl: '/images/celebrities/Danila Kozlovsky.png', exes: [] },
  { id: '55', type: 'celebrity', name: 'Svetlana Khodchenkova', imageUrl: '/images/celebrities/Svetlana Khodchenkova.png', exes: [] },
  { id: '56', type: 'celebrity', name: 'Alexander Petrov', imageUrl: '/images/celebrities/Alexander Petrov.png', exes: [] },
  { id: '57', type: 'celebrity', name: 'Polina Gagarina', imageUrl: '/images/celebrities/Polina Gagarina.png', exes: [] },

  // Cross-national couples/exes
  { id: '58', type: 'celebrity', name: 'Irina Shayk', imageUrl: '/images/celebrities/Irina Shayk.png', exes: ['Bradley Cooper'] },
  { id: '59', type: 'celebrity', name: 'Bradley Cooper', imageUrl: '/images/celebrities/Bradley Cooper.png', exes: ['Irina Shayk'] },
  { id: '60', type: 'celebrity', name: 'Anna Kournikova', imageUrl: '/images/celebrities/Anna Kournikova.png', partner: 'Enrique Iglesias', exes: [] },
  { id: '61', type: 'celebrity', name: 'Enrique Iglesias', imageUrl: '/images/celebrities/Enrique Iglesias.png', partner: 'Anna Kournikova', exes: [] },
  { id: '62', type: 'celebrity', name: 'Natalia Vodianova', imageUrl: '/images/celebrities/Natalia Vodianova.png', partner: 'Antoine Arnault', exes: [] },
  { id: '63', type: 'celebrity', name: 'Antoine Arnault', imageUrl: '/images/celebrities/Antoine Arnault.png', partner: 'Natalia Vodianova', exes: [] },

  // More fillers
  { id: '64', type: 'celebrity', name: 'Naomi Campbell', imageUrl: '/images/celebrities/Naomi Campbell.png', exes: [] },
  { id: '65', type: 'celebrity', name: 'Mickey Rourke', imageUrl: '/images/celebrities/Mickey Rourke.png', exes: [] },
  { id: '66', type: 'celebrity', name: 'Cristiano Ronaldo', imageUrl: '/images/celebrities/Cristiano Ronaldo.png', exes: ['Irina Shayk'] },
  { id: '67', type: 'celebrity', name: 'Dmitry Nagiev', imageUrl: '/images/celebrities/Dmitry Nagiev.png', exes: [] },
  { id: '68', type: 'celebrity', name: 'Sergey Shnurov', imageUrl: '/images/celebrities/Sergey Shnurov.png', exes: [] },
  { id: '69', type: 'celebrity', name: 'Renata Litvinova', imageUrl: '/images/celebrities/Renata Litvinova.png', exes: [] },
  { id: '70', type: 'celebrity', name: 'Adrien Brody', imageUrl: '/images/celebrities/Adrien Brody.png', exes: [] },
  { id: '71', type: 'celebrity', name: 'Jason Statham', imageUrl: '/images/celebrities/Jason Statham.png', exes: [] },
  { id: '72', type: 'celebrity', name: 'Keanu Reeves', imageUrl: '/images/celebrities/Keanu Reeves.png', exes: [] },
  { id: '73', type: 'celebrity', name: 'Dwayne Johnson', imageUrl: '/images/celebrities/Dwayne Johnson.png', exes: [] },
  { id: '74', type: 'celebrity', name: 'Jennifer Lopez', imageUrl: '/images/celebrities/Jennifer Lopez.png', exes: ['Ben Affleck'] },
  { id: '75', type: 'celebrity', name: 'Ben Affleck', imageUrl: '/images/celebrities/Ben Affleck.png', exes: ['Jennifer Lopez', 'Jennifer Garner'] },
  { id: '76', type: 'celebrity', name: 'Jennifer Garner', imageUrl: '/images/celebrities/Jennifer Garner.png', exes: ['Ben Affleck'] },
  { id: '77', type: 'celebrity', name: 'Will Smith', imageUrl: '/images/celebrities/Will Smith.png', partner: 'Jada Pinkett Smith', exes: [] },
  { id: '78', type: 'celebrity', name: 'Jada Pinkett Smith', imageUrl: '/images/celebrities/Jada Pinkett Smith.png', partner: 'Will Smith', exes: [] },
  { id: '79', type: 'celebrity', name: 'George Clooney', imageUrl: '/images/celebrities/George Clooney.png', exes: [] },
  { id: '80', type: 'celebrity', name: 'Julia Roberts', imageUrl: '/images/celebrities/Julia Roberts.png', exes: [] },
  { id: '81', type: 'celebrity', name: 'Basta', imageUrl: '/images/celebrities/Basta.png', exes: [] },
  { id: '82', type: 'celebrity', name: 'Egor Kreed', imageUrl: '/images/celebrities/Egor Kreed.png', exes: [] },
  { id: '83', type: 'celebrity', name: 'Timati', imageUrl: '/images/celebrities/Timati.png', exes: [] },
  { id: '84', type: 'celebrity', name: 'Olga Buzova', imageUrl: '/images/celebrities/Olga Buzova.png', exes: [] },
  { id: '85', type: 'celebrity', name: 'Khabib Nurmagomedov', imageUrl: '/images/celebrities/Khabib Nurmagomedov.png', exes: [] },
  { id: '86', type: 'celebrity', name: 'Alexander Ovechkin', imageUrl: '/images/celebrities/Alexander Ovechkin.png', exes: [] },
  { id: '87', type: 'celebrity', name: 'Maria Sharapova', imageUrl: '/images/celebrities/Maria Sharapova.png', exes: [] },
  { id: '88', type: 'celebrity', name: 'Mads Mikkelsen', imageUrl: '/images/celebrities/Mads Mikkelsen.png', exes: [] },
  { id: '89', type: 'celebrity', name: 'Tom Hardy', imageUrl: '/images/celebrities/Tom Hardy.png', exes: [] },
  { id: '90', type: 'celebrity', name: 'Cillian Murphy', imageUrl: '/images/celebrities/Cillian Murphy.png', exes: [] },
  { id: '91', type: 'celebrity', name: 'Emma Stone', imageUrl: '/images/celebrities/Emma Stone.png', exes: [] },
  { id: '92', type: 'celebrity', name: 'Ryan Gosling', imageUrl: '/images/celebrities/Ryan Gosling.png', exes: [] },
  { id: '93', type: 'celebrity', name: 'Katy Perry', imageUrl: '/images/celebrities/Katy Perry.png', exes: ['Orlando Bloom'] },
  { id: '94', type: 'celebrity', name: 'Orlando Bloom', imageUrl: '/images/celebrities/Orlando Bloom.png', exes: ['Katy Perry'] },
  { id: '95', type: 'celebrity', name: 'Cardi B', imageUrl: '/images/celebrities/Cardi B.png', exes: [] },
  { id: '96', type: 'celebrity', name: 'Nicki Minaj', imageUrl: '/images/celebrities/Nicki Minaj.png', exes: [] },
  { id: '97', type: 'celebrity', name: 'Billie Eilish', imageUrl: '/images/celebrities/Billie Eilish.png', exes: [] },
  { id: '98', type: 'celebrity', name: 'Kylie Jenner', imageUrl: '/images/celebrities/Kylie Jenner.png', exes: [] },
  { id: '99', type: 'celebrity', name: 'Robert Downey Jr.', imageUrl: '/images/celebrities/Robert Downey Jr..png', exes: [] },
  { id: '100', type: 'celebrity', name: 'Chris Pratt', imageUrl: '/images/celebrities/Chris Pratt.png', exes: [] }
];
