
import type { Celebrity } from './types';

export const celebritiesData: Celebrity[] = [
  // Hollywood Couples
  { id: '1', type: 'celebrity', name: { en: 'Justin Bieber', ru: 'Джастин Бибер' }, imageUrl: '/images/celebrities/Justin Bieber.png', partner: { en: 'Hailey Bieber', ru: 'Хейли Бибер' }, exes: [{ en: 'Selena Gomez', ru: 'Селена Гомес' }] },
  { id: '2', type: 'celebrity', name: { en: 'Hailey Bieber', ru: 'Хейли Бибер' }, imageUrl: '/images/celebrities/Hailey Bieber.png', partner: { en: 'Justin Bieber', ru: 'Джастин Бибер' }, exes: [] },
  { id: '3', type: 'celebrity', name: { en: 'Taylor Swift', ru: 'Тейлор Свифт' }, imageUrl: '/images/celebrities/Taylor Swift.png', partner: { en: 'Travis Kelce', ru: 'Трэвис Келси' }, exes: [{ en: 'Harry Styles', ru: 'Гарри Стайлс' }, { en: 'The Weeknd', ru: 'The Weeknd' }] },
  { id: '4', type: 'celebrity', name: { en: 'Travis Kelce', ru: 'Трэвис Келси' }, imageUrl: '/images/celebrities/Travis Kelce.png', partner: { en: 'Taylor Swift', ru: 'Тейлор Свифт' }, exes: [] },
  { id: '5', type: 'celebrity', name: { en: 'Blake Lively', ru: 'Блейк Лайвли' }, imageUrl: '/images/celebrities/Blake Lively.png', partner: { en: 'Ryan Reynolds', ru: 'Райан Рейнольдс' }, exes: [] },
  { id: '6', type: 'celebrity', name: { en: 'Ryan Reynolds', ru: 'Райан Рейнольдс' }, imageUrl: '/images/celebrities/Ryan Reynolds.png', partner: { en: 'Blake Lively', ru: 'Блейк Лайвли' }, exes: [] },
  { id: '7', type: 'celebrity', name: { en: 'Beyonce', ru: 'Бейонсе' }, imageUrl: '/images/celebrities/Beyonce.png', partner: { en: 'Jay-Z', ru: 'Jay-Z' }, exes: [] },
  { id: '8', type: 'celebrity', name: { en: 'Jay-Z', ru: 'Jay-Z' }, imageUrl: '/images/celebrities/Jay-Z.png', partner: { en: 'Beyonce', ru: 'Бейонсе' }, exes: [] },
  { id: '9', type: 'celebrity', name: { en: 'Tom Holland', ru: 'Том Холланд' }, imageUrl: '/images/celebrities/Tom Holland.png', partner: { en: 'Zendaya', ru: 'Зендея' }, exes: [] },
  { id: '10', type: 'celebrity', name: { en: 'Zendaya', ru: 'Зендея' }, imageUrl: '/images/celebrities/Zendaya.png', partner: { en: 'Tom Holland', ru: 'Том Холланд' }, exes: [] },
  { id: '25', type: 'celebrity', name: { en: 'Mila Kunis', ru: 'Мила Кунис' }, imageUrl: '/images/celebrities/Mila Kunis.png', partner: { en: 'Ashton Kutcher', ru: 'Эштон Кутчер' }, exes: [] },
  { id: '26', type: 'celebrity', name: { en: 'Ashton Kutcher', ru: 'Эштон Кутчер' }, imageUrl: '/images/celebrities/Ashton Kutcher.png', partner: { en: 'Mila Kunis', ru: 'Мила Кунис' }, exes: [] },
  { id: '27', type: 'celebrity', name: { en: 'Chrissy Teigen', ru: 'Крисси Тайген' }, imageUrl: '/images/celebrities/Chrissy Teigen.png', partner: { en: 'John Legend', ru: 'Джон Ледженд' }, exes: [] },
  { id: '28', type: 'celebrity', name: { en: 'John Legend', ru: 'Джон Ледженд' }, imageUrl: '/images/celebrities/John Legend.png', partner: { en: 'Chrissy Teigen', ru: 'Крисси Тайген' }, exes: [] },
  { id: '29', type: 'celebrity', name: { en: 'Jessica Biel', ru: 'Джессика Бил' }, imageUrl: '/images/celebrities/Jessica Biel.png', partner: { en: 'Justin Timberlake', ru: 'Джастин Тимберлейк' }, exes: [] },
  { id: '30', type: 'celebrity', name: { en: 'Justin Timberlake', ru: 'Джастин Тимберлейк' }, imageUrl: '/images/celebrities/Justin Timberlake.png', partner: { en: 'Jessica Biel', ru: 'Джессика Бил' }, exes: [{ en: 'Britney Spears', ru: 'Бритни Спирс' }] },

  // Hollywood Exes & Fillers
  { id: '11', type: 'celebrity', name: { en: 'Selena Gomez', ru: 'Селена Гомес' }, imageUrl: '/images/celebrities/Selena Gomez.png', exes: [{ en: 'Justin Bieber', ru: 'Джастин Бибер' }, { en: 'The Weeknd', ru: 'The Weeknd' }] },
  { id: '12', type: 'celebrity', name: { en: 'Shawn Mendes', ru: 'Шон Мендес' }, imageUrl: '/images/celebrities/Shawn Mendes.png', exes: [] },
  { id: '13', type: 'celebrity', name: { en: 'Drake', ru: 'Дрейк' }, imageUrl: '/images/celebrities/Drake.png', exes: [] },
  { id: '14', type: 'celebrity', name: { en: 'Kendall Jenner', ru: 'Кендалл Дженнер' }, imageUrl: '/images/celebrities/Kendall Jenner.png', exes: [] },
  { id: '15', type: 'celebrity', name: { en: 'Leonardo DiCaprio', ru: 'Леонардо Ди Каприо' }, imageUrl: '/images/celebrities/Leonardo DiCaprio.png', exes: [] },
  { id: '16', type: 'celebrity', name: { en: 'Scarlett Johansson', ru: 'Скарлетт Йоханссон' }, imageUrl: '/images/celebrities/Scarlett Johansson.png', exes: [] },
  { id: '17', type: 'celebrity', name: { en: 'Harry Styles', ru: 'Гарри Стайлс' }, imageUrl: '/images/celebrities/Harry Styles.png', exes: [{ en: 'Taylor Swift', ru: 'Тейлор Свифт' }] },
  { id: '18', type: 'celebrity', name: { en: 'Rihanna', ru: 'Рианна' }, imageUrl: '/images/celebrities/Rihanna.png', exes: [] },
  { id: '19', type: 'celebrity', name: { en: 'The Weeknd', ru: 'The Weeknd' }, imageUrl: '/images/celebrities/The Weeknd.png', exes: [{ en: 'Selena Gomez', ru: 'Селена Гомес' }, { en: 'Taylor Swift', ru: 'Тейлор Свифт' }] },
  { id: '20', type: 'celebrity', name: { en: 'Gigi Hadid', ru: 'Джиджи Хадид' }, imageUrl: '/images/celebrities/Gigi Hadid.png', exes: [] },
  { id: '21', type: 'celebrity', name: { en: 'Dua Lipa', ru: 'Дуа Липа' }, imageUrl: '/images/celebrities/Dua Lipa.png', exes: [] },
  { id: '22', type: 'celebrity', name: { en: 'Chris Evans', ru: 'Крис Эванс' }, imageUrl: '/images/celebrities/Chris Evans.png', exes: [] },
  { id: '23', type: 'celebrity', name: { en: 'Jennifer Lawrence', ru: 'Дженнифер Лоуренс' }, imageUrl: '/images/celebrities/Jennifer Lawrence.png', exes: [] },
  { id: '24', type: 'celebrity', name: { en: 'Timothée Chalamet', ru: 'Тимоти Шаламе' }, imageUrl: '/images/celebrities/Timothée Chalamet.png', exes: [] },
  { id: '31', type: 'celebrity', name: { en: 'Kim Kardashian', ru: 'Ким Кардашьян' }, imageUrl: '/images/celebrities/Kim Kardashian.png', exes: [{ en: 'Kanye West', ru: 'Канье Уэст' }] },
  { id: '32', type: 'celebrity', name: { en: 'Kanye West', ru: 'Канье Уэст' }, imageUrl: '/images/celebrities/Kanye West.png', exes: [{ en: 'Kim Kardashian', ru: 'Ким Кардашьян' }] },
  { id: '33', type: 'celebrity', name: { en: 'Brad Pitt', ru: 'Брэд Питт' }, imageUrl: '/images/celebrities/Brad Pitt.png', exes: [{ en: 'Angelina Jolie', ru: 'Анджелина Джоли' }, { en: 'Jennifer Aniston', ru: 'Дженнифер Энистон' }] },
  { id: '34', type: 'celebrity', name: { en: 'Angelina Jolie', ru: 'Анджелина Джоли' }, imageUrl: '/images/celebrities/Angelina Jolie.png', exes: [{ en: 'Brad Pitt', ru: 'Брэд Питт' }] },
  { id: '35', type: 'celebrity', name: { en: 'Jennifer Aniston', ru: 'Дженнифер Энистон' }, imageUrl: '/images/celebrities/Jennifer Aniston.png', exes: [{ en: 'Brad Pitt', ru: 'Брэд Питт' }] },
  { id: '36', type: 'celebrity', name: { en: 'Britney Spears', ru: 'Бритни Спирс' }, imageUrl: '/images/celebrities/Britney Spears.png', exes: [{ en: 'Justin Timberlake', ru: 'Джастин Тимберлейк' }] },
  { id: '37', type: 'celebrity', name: { en: 'Ariana Grande', ru: 'Ариана Гранде' }, imageUrl: '/images/celebrities/Ariana Grande.png', exes: [] },
  { id: '38', type: 'celebrity', name: { en: 'Lady Gaga', ru: 'Леди Гага' }, imageUrl: '/images/celebrities/Lady Gaga.png', exes: [] },
  { id: '39', type: 'celebrity', name: { en: 'Chris Hemsworth', ru: 'Крис Хемсворт' }, imageUrl: '/images/celebrities/Chris Hemsworth.png', exes: [] },
  { id: '40', type: 'celebrity', name: { en: 'Margot Robbie', ru: 'Марго Робби' }, imageUrl: '/images/celebrities/Margot Robbie.png', exes: [] },

  // Russian Couples
  { id: '41', type: 'celebrity', name: { en: 'Alla Pugacheva', ru: 'Алла Пугачева' }, imageUrl: '/images/celebrities/Alla Pugacheva.png', partner: { en: 'Maxim Galkin', ru: 'Максим Галкин' }, exes: [{ en: 'Philipp Kirkorov', ru: 'Филипп Киркоров' }] },
  { id: '42', type: 'celebrity', name: { en: 'Maxim Galkin', ru: 'Максим Галкин' }, imageUrl: '/images/celebrities/Maxim Galkin.png', partner: { en: 'Alla Pugacheva', ru: 'Алла Пугачева' }, exes: [] },
  { id: '43', type: 'celebrity', name: { en: 'Pavel Volya', ru: 'Павел Воля' }, imageUrl: '/images/celebrities/Pavel Volya.png', partner: { en: 'Laysan Utiasheva', ru: 'Ляйсан Утяшева' }, exes: [] },
  { id: '44', type: 'celebrity', name: { en: 'Laysan Utiasheva', ru: 'Ляйсан Утяшева' }, imageUrl: '/images/celebrities/Laysan Utiasheva.png', partner: { en: 'Pavel Volya', ru: 'Павел Воля' }, exes: [] },
  { id: '45', type: 'celebrity', name: { en: 'Ksenia Sobchak', ru: 'Ксения Собчак' }, imageUrl: '/images/celebrities/Ksenia Sobchak.png', partner: { en: 'Konstantin Bogomolov', ru: 'Константин Богомолов' }, exes: [{ en: 'Maxim Vitorgan', ru: 'Максим Виторган' }] },
  { id: '46', type: 'celebrity', name: { en: 'Konstantin Bogomolov', ru: 'Константин Богомолов' }, imageUrl: '/images/celebrities/Konstantin Bogomolov.png', partner: { en: 'Ksenia Sobchak', ru: 'Ксения Собчак' }, exes: [] },
  { id: '47', type: 'celebrity', name: { en: 'Fedor Bondarchuk', ru: 'Фёдор Бондарчук' }, imageUrl: '/images/celebrities/Fedor Bondarchuk.png', partner: { en: 'Paulina Andreeva', ru: 'Паулина Андреева' }, exes: [] },
  { id: '48', type: 'celebrity', name: { en: 'Paulina Andreeva', ru: 'Паулина Андреева' }, imageUrl: '/images/celebrities/Paulina Andreeva.png', partner: { en: 'Fedor Bondarchuk', ru: 'Фёдор Бондарчук' }, exes: [] },
  { id: '49', type: 'celebrity', name: { en: 'Agata Muceniece', ru: 'Агата Муцениеце' }, imageUrl: '/images/celebrities/Agata Muceniece.png', exes: [{ en: 'Pavel Priluchny', ru: 'Павел Прилучный' }] },
  { id: '50', type: 'celebrity', name: { en: 'Pavel Priluchny', ru: 'Павел Прилучный' }, imageUrl: '/images/celebrities/Pavel Priluchny.png', exes: [{ en: 'Agata Muceniece', ru: 'Агата Муцениеце' }] },

  // Russian Exes & Fillers
  { id: '51', type: 'celebrity', name: { en: 'Philipp Kirkorov', ru: 'Филипп Киркоров' }, imageUrl: '/images/celebrities/Philipp Kirkorov.png', exes: [{ en: 'Alla Pugacheva', ru: 'Алла Пугачева' }] },
  { id: '52', type: 'celebrity', name: { en: 'Maxim Vitorgan', ru: 'Максим Виторган' }, imageUrl: '/images/celebrities/Maxim Vitorgan.png', exes: [{ en: 'Ksenia Sobchak', ru: 'Ксения Собчак' }] },
  { id: '53', type: 'celebrity', name: { en: 'Ivan Urgant', ru: 'Иван Ургант' }, imageUrl: '/images/celebrities/Ivan Urgant.png', exes: [] },
  { id: '54', type: 'celebrity', name: { en: 'Danila Kozlovsky', ru: 'Данила Козловский' }, imageUrl: '/images/celebrities/Danila Kozlovsky.png', exes: [] },
  { id: '55', type: 'celebrity', name: { en: 'Svetlana Khodchenkova', ru: 'Светлана Ходченкова' }, imageUrl: '/images/celebrities/Svetlana Khodchenkova.png', exes: [] },
  { id: '56', type: 'celebrity', name: { en: 'Alexander Petrov', ru: 'Александр Петров' }, imageUrl: '/images/celebrities/Alexander Petrov.png', exes: [] },
  { id: '57', type: 'celebrity', name: { en: 'Polina Gagarina', ru: 'Полина Гагарина' }, imageUrl: '/images/celebrities/Polina Gagarina.png', exes: [] },

  // Cross-national couples/exes
  { id: '58', type: 'celebrity', name: { en: 'Irina Shayk', ru: 'Ирина Шейк' }, imageUrl: '/images/celebrities/Irina Shayk.png', exes: [{ en: 'Bradley Cooper', ru: 'Брэдли Купер' }] },
  { id: '59', type: 'celebrity', name: { en: 'Bradley Cooper', ru: 'Брэдли Купер' }, imageUrl: '/images/celebrities/Bradley Cooper.png', exes: [{ en: 'Irina Shayk', ru: 'Ирина Шейк' }] },
  { id: '60', type: 'celebrity', name: { en: 'Anna Kournikova', ru: 'Анна Курникова' }, imageUrl: '/images/celebrities/Anna Kournikova.png', partner: { en: 'Enrique Iglesias', ru: 'Энрике Иглесиас' }, exes: [] },
  { id: '61', type: 'celebrity', name: { en: 'Enrique Iglesias', ru: 'Энрике Иглесиас' }, imageUrl: '/images/celebrities/Enrique Iglesias.png', partner: { en: 'Anna Kournikova', ru: 'Анна Курникова' }, exes: [] },
  { id: '62', type: 'celebrity', name: { en: 'Natalia Vodianova', ru: 'Наталья Водянова' }, imageUrl: '/images/celebrities/Natalia Vodianova.png', partner: { en: 'Antoine Arnault', ru: 'Антуан Арно' }, exes: [] },
  { id: '63', type: 'celebrity', name: { en: 'Antoine Arnault', ru: 'Антуан Арно' }, imageUrl: '/images/celebrities/Antoine Arnault.png', partner: { en: 'Natalia Vodianova', ru: 'Наталья Водянова' }, exes: [] },

  // More fillers
  { id: '64', type: 'celebrity', name: { en: 'Naomi Campbell', ru: 'Наоми Кэмпбелл' }, imageUrl: '/images/celebrities/Naomi Campbell.png', exes: [] },
  { id: '65', type: 'celebrity', name: { en: 'Mickey Rourke', ru: 'Микки Рурк' }, imageUrl: '/images/celebrities/Mickey Rourke.png', exes: [] },
  { id: '66', type: 'celebrity', name: { en: 'Cristiano Ronaldo', ru: 'Криштиану Роналду' }, imageUrl: '/images/celebrities/Cristiano Ronaldo.png', exes: [{ en: 'Irina Shayk', ru: 'Ирина Шейк' }] },
  { id: '67', type: 'celebrity', name: { en: 'Dmitry Nagiev', ru: 'Дмитрий Нагиев' }, imageUrl: '/images/celebrities/Dmitry Nagiev.png', exes: [] },
  { id: '68', type: 'celebrity', name: { en: 'Sergey Shnurov', ru: 'Сергей Шнуров' }, imageUrl: '/images/celebrities/Sergey Shnurov.png', exes: [] },
  { id: '69', type: 'celebrity', name: { en: 'Renata Litvinova', ru: 'Рената Литвинова' }, imageUrl: '/images/celebrities/Renata Litvinova.png', exes: [] },
  { id: '70', type: 'celebrity', name: { en: 'Adrien Brody', ru: 'Эдриен Броуди' }, imageUrl: '/images/celebrities/Adrien Brody.png', exes: [] },
  { id: '71', type: 'celebrity', name: { en: 'Jason Statham', ru: 'Джейсон Стэйтем' }, imageUrl: '/images/celebrities/Jason Statham.png', exes: [] },
  { id: '72', type: 'celebrity', name: { en: 'Keanu Reeves', ru: 'Киану Ривз' }, imageUrl: '/images/celebrities/Keanu Reeves.png', exes: [] },
  { id: '73', type: 'celebrity', name: { en: 'Dwayne Johnson', ru: 'Дуэйн Джонсон' }, imageUrl: '/images/celebrities/Dwayne Johnson.png', exes: [] },
  { id: '74', type: 'celebrity', name: { en: 'Jennifer Lopez', ru: 'Дженнифер Лопес' }, imageUrl: '/images/celebrities/Jennifer Lopez.png', exes: [{ en: 'Ben Affleck', ru: 'Бен Аффлек' }] },
  { id: '75', type: 'celebrity', name: { en: 'Ben Affleck', ru: 'Бен Аффлек' }, imageUrl: '/images/celebrities/Ben Affleck.png', exes: [{ en: 'Jennifer Lopez', ru: 'Дженнифер Лопес' }, { en: 'Jennifer Garner', ru: 'Дженнифер Гарнер' }] },
  { id: '76', type: 'celebrity', name: { en: 'Jennifer Garner', ru: 'Дженнифер Гарнер' }, imageUrl: '/images/celebrities/Jennifer Garner.png', exes: [{ en: 'Ben Affleck', ru: 'Бен Аффлек' }] },
  { id: '77', type: 'celebrity', name: { en: 'Will Smith', ru: 'Уилл Смит' }, imageUrl: '/images/celebrities/Will Smith.png', partner: { en: 'Jada Pinkett Smith', ru: 'Джада Пинкетт-Смит' }, exes: [] },
  { id: '78', type: 'celebrity', name: { en: 'Jada Pinkett Smith', ru: 'Джада Пинкетт-Смит' }, imageUrl: '/images/celebrities/Jada Pinkett Smith.png', partner: { en: 'Will Smith', ru: 'Уилл Смит' }, exes: [] },
  { id: '79', type: 'celebrity', name: { en: 'George Clooney', ru: 'Джордж Клуни' }, imageUrl: '/images/celebrities/George Clooney.png', exes: [] },
  { id: '80', type: 'celebrity', name: { en: 'Julia Roberts', ru: 'Джулия Робертс' }, imageUrl: '/images/celebrities/Julia Roberts.png', exes: [] },
  { id: '81', type: 'celebrity', name: { en: 'Basta', ru: 'Баста' }, imageUrl: '/images/celebrities/Basta.png', exes: [] },
  { id: '82', type: 'celebrity', name: { en: 'Egor Kreed', ru: 'Егор Крид' }, imageUrl: '/images/celebrities/Egor Kreed.png', exes: [] },
  { id: '83', type: 'celebrity', name: { en: 'Timati', ru: 'Тимати' }, imageUrl: '/images/celebrities/Timati.png', exes: [] },
  { id: '84', type: 'celebrity', name: { en: 'Olga Buzova', ru: 'Ольга Бузова' }, imageUrl: '/images/celebrities/Olga Buzova.png', exes: [] },
  { id: '85', type: 'celebrity', name: { en: 'Khabib Nurmagomedov', ru: 'Хабиб Нурмагомедов' }, imageUrl: '/images/celebrities/Khabib Nurmagomedov.png', exes: [] },
  { id: '86', type: 'celebrity', name: { en: 'Alexander Ovechkin', ru: 'Александр Овечкин' }, imageUrl: '/images/celebrities/Alexander Ovechkin.png', exes: [] },
  { id: '87', type: 'celebrity', name: { en: 'Maria Sharapova', ru: 'Мария Шарапова' }, imageUrl: '/images/celebrities/Maria Sharapova.png', exes: [] },
  { id: '88', type: 'celebrity', name: { en: 'Mads Mikkelsen', ru: 'Мадс Миккельсен' }, imageUrl: '/images/celebrities/Mads Mikkelsen.png', exes: [] },
  { id: '89', type: 'celebrity', name: { en: 'Tom Hardy', ru: 'Том Харди' }, imageUrl: '/images/celebrities/Tom Hardy.png', exes: [] },
  { id: '90', type: 'celebrity', name: { en: 'Cillian Murphy', ru: 'Киллиан Мёрфи' }, imageUrl: '/images/celebrities/Cillian Murphy.png', exes: [] },
  { id: '91', type: 'celebrity', name: { en: 'Emma Stone', ru: 'Эмма Стоун' }, imageUrl: '/images/celebrities/Emma Stone.png', exes: [] },
  { id: '92', type: 'celebrity', name: { en: 'Ryan Gosling', ru: 'Райан Гослинг' }, imageUrl: '/images/celebrities/Ryan Gosling.png', exes: [] },
  { id: '93', type: 'celebrity', name: { en: 'Katy Perry', ru: 'Кэти Перри' }, imageUrl: '/images/celebrities/Katy Perry.png', exes: [{ en: 'Orlando Bloom', ru: 'Орландо Блум' }] },
  { id: '94', type: 'celebrity', name: { en: 'Orlando Bloom', ru: 'Орландо Блум' }, imageUrl: '/images/celebrities/Orlando Bloom.png', exes: [{ en: 'Katy Perry', ru: 'Кэти Перри' }] },
  { id: '95', type: 'celebrity', name: { en: 'Cardi B', ru: 'Карди Би' }, imageUrl: '/images/celebrities/Cardi B.png', exes: [] },
  { id: '96', type: 'celebrity', name: { en: 'Nicki Minaj', ru: 'Ники Минаж' }, imageUrl: '/images/celebrities/Nicki Minaj.png', exes: [] },
  { id: '97', type: 'celebrity', name: { en: 'Billie Eilish', ru: 'Билли Айлиш' }, imageUrl: '/images/celebrities/Billie Eilish.png', exes: [] },
  { id: '98', type: 'celebrity', name: { en: 'Kylie Jenner', ru: 'Кайли Дженнер' }, imageUrl: '/images/celebrities/Kylie Jenner.png', exes: [] },
  { id: '99', type: 'celebrity', name: { en: 'Robert Downey Jr.', ru: 'Роберт Дауни-младший' }, imageUrl: '/images/celebrities/Robert Downey Jr..png', exes: [] },
  { id: '100', type: 'celebrity', name: { en: 'Chris Pratt', ru: 'Крис Прэтт' }, imageUrl: '/images/celebrities/Chris Pratt.png', exes: [] }
];
